#!/bin/bash

SCRIPTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPTPATH

if python -V | grep -q "Python 3" ;then
    PYTHON="python2"
else
    PYTHON="python"
fi


if [ -f code/version.txt ]; then
    VERSION=`cat code/version.txt`
else
    VERSION="default"
fi


if [ ! -d "code/$VERSION" ]; then
    VERSION="default"
fi
echo "XX-Net version:$VERSION"


# launch xx-net service by ignore hungup signal
function launchWithNoHungup() {
    nohup ${PYTHON} code/${VERSION}/launcher/start.py 2&> /dev/null &
}

# launch xx-net service by hungup signal
function launchWithHungup() {
    ${PYTHON} code/${VERSION}/launcher/start.py
}

# get operating system name
os_name=`uname -s`

# Install Packages
if [ $os_name = 'Linux' ]; then
    echo 'Install python-openssl and libnss3-tools for your system'
    if [ `which apt-get | wc -l` != 0 ]; then
        if [ `dpkg-query -l | grep python-openssl | wc -l` == 0 ]; then
            sudo apt-get install -y python-openssl
        fi
    elif [ `which dnf | wc -l` != 0 ]; then
        if [ `dnf -q list installed | grep pyOpenSSL | wc -l` == 0 ]; then
            sudo dnf install -y pyOpenSSL
        fi
    elif [ `which yum | wc -l` != 0 ]; then
        if [ `yum -q list installed | grep pyOpenSSL | wc -l` == 0 ]; then
            sudo yum install -y pyOpenSSL
        fi
    elif [ `which pacman | wc -l` != 0 ]; then
        if [ `pacman -Q | grep python2-pyopenssl | wc -l` == 0 ]; then
            sudo pacman -S --noconfirm openssl python2-pyopenssl
        fi
    # Do Someting for OpenSUSE
    # Do Someting for OpenWRT
    fi
elif [ $os_name = 'Darwin' ]; then
    if [ `python -c 'import OpenSSL; print(OpenSSL.SSL.OPENSSL_VERSION_NUMBER > 0x1000200)' 2> /dev/null | grep True | wc -l` != 1 ]; then
        PYTHON="/usr/bin/python2.7"
        echo 'Warning: using system python'
        echo 'Please install python from Homebrew or MacPorts for HTTP/2 support'
        echo 'brew install python'
        echo 'pip install pyOpenSSL'
    fi
fi

# Start Application
if [ $os_name = 'Darwin' ] && ! [ "$1" = '-hungup' ]; then
    launchWithNoHungup
else
    launchWithHungup
fi
